/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import java.awt.Color;
import javax.swing.JMenuItem;

/**
 *
 * @author Marko
 */
public class ServerForm extends javax.swing.JFrame {

    /**
     * Creates new form ServerForm
     */
    public ServerForm() {
        initComponents();
        setLocationRelativeTo(null);
        zaustavljen();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStatus = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        lblIpAdresa = new javax.swing.JLabel();
        txtIpAdresa = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnPokreniServer = new javax.swing.JMenuItem();
        btnZaustaviServer = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        btnPodesavanje = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");

        lblStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblStatus.setText("Status:");

        txtStatus.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtStatus.setText("jLabel2");

        lblIpAdresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblIpAdresa.setText("Lokalna IP adresa:");

        txtIpAdresa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtIpAdresa.setText("jLabel4");

        jMenu1.setText("Server");

        btnPokreniServer.setText("Pokreni");
        jMenu1.add(btnPokreniServer);

        btnZaustaviServer.setText(" Zaustavi");
        jMenu1.add(btnZaustaviServer);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Podesavanja");

        btnPodesavanje.setText("Podesavanja servera i baze");
        jMenu2.add(btnPodesavanje);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIpAdresa)
                    .addComponent(lblStatus))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIpAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatus)
                    .addComponent(txtStatus))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIpAdresa)
                    .addComponent(txtIpAdresa))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnPodesavanje;
    private javax.swing.JMenuItem btnPokreniServer;
    private javax.swing.JMenuItem btnZaustaviServer;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblIpAdresa;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel txtIpAdresa;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getBtnPodesavanja() {
        return btnPodesavanje;
    }

    public JMenuItem getBtnPokreniServer() {
        return btnPokreniServer;
    }

    public JMenuItem getBtnZaustaviServer() {
        return btnZaustaviServer;
    }

    public void zaustavljen() {
        lblIpAdresa.setVisible(false);
        txtIpAdresa.setVisible(false);
        txtStatus.setText("Zaustavljen");
        txtStatus.setForeground(Color.red);
        btnPodesavanje.setEnabled(true);
        btnPokreniServer.setEnabled(true);
        btnZaustaviServer.setEnabled(false);
    }

    public void pokrenut(String adresa) {
        lblIpAdresa.setVisible(true);
        txtIpAdresa.setVisible(true);
        txtStatus.setText("Pokrenut");
        txtStatus.setForeground(Color.GREEN);
        txtIpAdresa.setText(adresa);
        btnPodesavanje.setEnabled(false);
        btnPokreniServer.setEnabled(false);
        btnZaustaviServer.setEnabled(true);
    }

}
