/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import javax.swing.JLabel;
import javax.swing.JMenuItem;

/**
 *
 * @author Marko
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTrenutniKorisnik = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuVozila = new javax.swing.JMenu();
        menuItemUnosVozila = new javax.swing.JMenuItem();
        menuItemPretragaVozila = new javax.swing.JMenuItem();
        menuKlijenti = new javax.swing.JMenu();
        menuItemUnosKlijenta = new javax.swing.JMenuItem();
        menuItemPretragaKlijenata = new javax.swing.JMenuItem();
        menuZaduzenja = new javax.swing.JMenu();
        menuItemUnosZaduzenja = new javax.swing.JMenuItem();
        menuItemPretragaZaduzenja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rent a car");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Korisnik :");

        lblTrenutniKorisnik.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        menuVozila.setText("Vozila");

        menuItemUnosVozila.setText("Unos Vozila");
        menuVozila.add(menuItemUnosVozila);

        menuItemPretragaVozila.setText("Pretraga vozila");
        menuVozila.add(menuItemPretragaVozila);

        jMenuBar1.add(menuVozila);

        menuKlijenti.setText("Klijenti");

        menuItemUnosKlijenta.setText("Unos klijenta");
        menuKlijenti.add(menuItemUnosKlijenta);

        menuItemPretragaKlijenata.setText(" Pretraga Klijenata");
        menuKlijenti.add(menuItemPretragaKlijenata);

        jMenuBar1.add(menuKlijenti);

        menuZaduzenja.setText("Zaduzenja");

        menuItemUnosZaduzenja.setText("Unos Zaduzenja");
        menuZaduzenja.add(menuItemUnosZaduzenja);

        menuItemPretragaZaduzenja.setText("Pretraga Zaduzenja");
        menuZaduzenja.add(menuItemPretragaZaduzenja);

        jMenuBar1.add(menuZaduzenja);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrenutniKorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTrenutniKorisnik;
    private javax.swing.JMenuItem menuItemPretragaKlijenata;
    private javax.swing.JMenuItem menuItemPretragaVozila;
    private javax.swing.JMenuItem menuItemPretragaZaduzenja;
    private javax.swing.JMenuItem menuItemUnosKlijenta;
    private javax.swing.JMenuItem menuItemUnosVozila;
    private javax.swing.JMenuItem menuItemUnosZaduzenja;
    private javax.swing.JMenu menuKlijenti;
    private javax.swing.JMenu menuVozila;
    private javax.swing.JMenu menuZaduzenja;
    // End of variables declaration//GEN-END:variables

    public JMenuItem getMenuItemPretragaKlijenata() {
        return menuItemPretragaKlijenata;
    }

    public JMenuItem getMenuItemPretragaVozila() {
        return menuItemPretragaVozila;
    }

    public JMenuItem getMenuItemPretragaZaduzenja() {
        return menuItemPretragaZaduzenja;
    }

    public JMenuItem getMenuItemUnosKlijenta() {
        return menuItemUnosKlijenta;
    }

    public JMenuItem getMenuItemUnosVozila() {
        return menuItemUnosVozila;
    }

    public JMenuItem getMenuItemUnosZaduzenja() {
        return menuItemUnosZaduzenja;
    }

    public JLabel getLblTrenutniKorisnik() {
        return lblTrenutniKorisnik;
    }

}
